// <auto-generated />
namespace props.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addPets1333 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPets1333));
        
        string IMigrationMetadata.Id
        {
            get { return "201804200655062_addPets1333"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
